# Generated by Django 3.1.6 on 2021-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogico_hs',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analogico_hs0',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analogico_hs1',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analogico_hs2',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analogico_hs3',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analogico_hs4',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analogico_hs5',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tk',
            name='current_data',
            field=models.JSONField(null=True),
        ),
    ]
