# Generated by Django 2.2.6 on 2020-02-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MbEsclavo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puerto', models.CharField(default='sa', max_length=3)),
                ('Velocidad', models.IntegerField(choices=[('A', 9600), ('B', 19200), ('C', 38400)], default=19200)),
                ('Paridad', models.CharField(choices=[('PAR', 'Par'), ('IMPAR', 'Impar')], default='PAR', max_length=5)),
                ('Reintentos', models.IntegerField(default=3)),
                ('IdEsclavo', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MbMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puerto', models.CharField(default='s0', max_length=3)),
                ('Velocidad', models.IntegerField(choices=[('A', 9600), ('B', 19200), ('C', 38400)], default='A')),
                ('Paridad', models.CharField(choices=[('PAR', 'Par'), ('IMPAR', 'Impar')], default='PAR', max_length=5)),
                ('Reintentos', models.IntegerField(default=3)),
                ('Tipo', models.CharField(choices=[('TCP', 'MBTCP'), ('RTU', 'MBRTU')], default='TCP', max_length=3)),
                ('IdDevice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatioTanques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_de_tk', models.CharField(choices=[('CV', 'Cilindrico Vertical'), ('CH', 'Cilindrico Horizontal'), ('ES', 'Esferico'), ('TF', 'Techo  Flotante')], default='TF', max_length=2)),
                ('id_patiotanques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.PatioTanques')),
            ],
        ),
        migrations.CreateModel(
            name='Tct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lt0', models.DecimalField(decimal_places=3, max_digits=3)),
                ('Lt1', models.DecimalField(decimal_places=3, max_digits=3)),
                ('Lt2', models.DecimalField(decimal_places=3, max_digits=3)),
                ('Tov', models.FloatField(default=1.0)),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tk')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=42)),
                ('Descriptor', models.CharField(max_length=120)),
                ('TipoDato', models.CharField(choices=[('A', 'Analogico'), ('D', 'Digital')], default='A', max_length=1)),
                ('Habilitar', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField()),
                ('Pv', models.FloatField(default=1.0)),
                ('TipoVariable', models.CharField(choices=[('O', 'Origen'), ('B', 'Basica'), ('C', 'Calculada')], default='B', max_length=1)),
                ('id_Tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tk')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctsh', models.FloatField(default=1.0)),
                ('fra', models.FloatField(default=1.0)),
                ('ctpl', models.FloatField(default=1.0)),
                ('id_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tk')),
            ],
        ),
        migrations.CreateModel(
            name='Digital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('SO_Habilitar', models.BooleanField(default=True)),
                ('S1_Habilitar', models.BooleanField(default=True)),
                ('Id_Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Analogico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorMinimo', models.FloatField(default=1.0)),
                ('ValorMaximo', models.FloatField(default=2.0)),
                ('Unidad', models.CharField(max_length=5)),
                ('HH_Habilitar', models.BooleanField(default=True)),
                ('H_Habilitar', models.BooleanField(default=True)),
                ('LL_Habilitar', models.BooleanField(default=True)),
                ('L_Habilitar', models.BooleanField(default=True)),
                ('HisteresisHabilitar', models.BooleanField(default=True)),
                ('ROC_Habiltar', models.BooleanField(default=True)),
                ('Pv', models.FloatField(default=1.0)),
                ('HH', models.FloatField(default=1.0)),
                ('H', models.FloatField(default=1.0)),
                ('LL', models.FloatField(default=1.0)),
                ('L', models.FloatField(default=1.0)),
                ('Histeresis', models.FloatField(default=1.0)),
                ('ROC', models.FloatField(default=1.0)),
                ('Id_Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tag')),
            ],
        ),
    ]
