# Generated by Django 3.1.6 on 2021-04-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('patios', models.ManyToManyField(to='acq.PatioTanque')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
