# Generated by Django 3.0.3 on 2020-09-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tct',
            old_name='Tov_1',
            new_name='Tov0',
        ),
        migrations.RenameField(
            model_name='tct',
            old_name='Tov_2',
            new_name='Tov1',
        ),
    ]
