# Generated by Django 3.2.6 on 2021-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk',
            name='ctpl',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tk',
            name='ctsh',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tk',
            name='fra',
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name='Factor',
        ),
    ]
