# Generated by Django 3.0.3 on 2020-02-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital',
            old_name='S1_Habilitar',
            new_name='S1A_Habilitar',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='SO_Habilitar',
            new_name='SOA_Habilitar',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='TipoDato',
        ),
    ]
