# Generated by Django 2.2.6 on 2020-02-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatioTanques',
            new_name='PatioTanque',
        ),
        migrations.RenameField(
            model_name='tk',
            old_name='id_patiotanques',
            new_name='id_patioTanque',
        ),
    ]
