# Generated by Django 3.1.6 on 2021-05-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='current_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tk',
            name='id_aor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acq.aor', verbose_name='AREA'),
        ),
    ]
