# Generated by Django 3.2 on 2021-05-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0002_auto_20210512_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='id_aor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acq.aor', verbose_name='Area'),
        ),
    ]
