# Generated by Django 2.2.6 on 2020-02-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0002_auto_20200205_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patiotanque',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='Pv',
            new_name='ValorInicial',
        ),
    ]
