# Generated by Django 3.0.3 on 2020-11-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0002_auto_20201027_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patiotanque',
            options={'ordering': ['Nombre']},
        ),
        migrations.AlterModelOptions(
            name='tk',
            options={'ordering': ['Nombre']},
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta1',
            field=models.CharField(choices=[('lt', 'Nivel Medido'), ('pt', 'Presión'), ('tt', 'Temperatura'), ('TOV', 'Volumen Total Observado '), ('NA', 'No Asignado'), ('GSV', 'Volumen Bruto Estandar'), ('NSV', 'Volumen Neto Estandar'), ('LTA', 'Nivel de Agua Libre')], default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta2',
            field=models.CharField(default='', max_length=32, verbose_name='Tag del instrumento en campo o P&ID'),
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta3',
            field=models.CharField(default='', max_length=32, verbose_name='ETIQETA PARA USUARIOS'),
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta4',
            field=models.CharField(default='', max_length=32, verbose_name='ETIQETA PARA USUARIOS'),
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta5',
            field=models.CharField(default='', max_length=32, verbose_name='ETIQETA PARA USUARIOS'),
        ),
        migrations.AddField(
            model_name='tag',
            name='etiqueta6',
            field=models.CharField(default='', max_length=32, verbose_name='ETIQETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tk',
            name='Nombre',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
