# Generated by Django 3.0.3 on 2020-02-23 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0002_auto_20200221_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analogico_seg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateField(default=datetime.date.today)),
                ('id_Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tk')),
            ],
        ),
    ]
