# Generated by Django 2.2.6 on 2020-02-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0003_auto_20200210_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analogico',
            old_name='Pv',
            new_name='ValorInicial',
        ),
        migrations.RenameField(
            model_name='digital',
            old_name='Estado',
            new_name='EstadoInicial',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='ValorInicial',
        ),
        migrations.AddField(
            model_name='digital',
            name='S0A',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digital',
            name='S1A',
            field=models.BooleanField(default=True),
        ),
    ]
