# Generated by Django 3.2 on 2021-05-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0003_alter_tk_id_aor'),
        ('acq', '0003_userprofile_aor'),
    ]

    operations = [
    ]
