# Generated by Django 3.0.3 on 2020-02-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0003_analogico_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogico_seg',
            name='Pv',
            field=models.FloatField(default=1.0),
        ),
    ]
