# Generated by Django 3.0.3 on 2020-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0003_auto_20201122_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='etiqueta2',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='Tag del instrumento en campo o P&ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta3',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta4',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta5',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta6',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
    ]
