# Generated by Django 3.2.8 on 2021-10-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0003_auto_20210830_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogico',
            name='H',
            field=models.FloatField(default=16.0, verbose_name='ALTO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='HH',
            field=models.FloatField(default=18.0, verbose_name='ALTO ALTO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='HH_Habilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma ALTO ALTO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='H_Habilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma ALTO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='Histeresis',
            field=models.FloatField(default=1.0, verbose_name='HISTERESIS'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='HisteresisHabilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma HISTERESIS'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='L',
            field=models.FloatField(default=6.0, verbose_name='BAJO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='LL',
            field=models.FloatField(default=4.0, verbose_name='BAJO BAJO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='LL_Habilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma BAJO BAJO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='L_Habilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma BAJO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ROC',
            field=models.FloatField(default=1.0, verbose_name='RATA EL CAMBIO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ROC_Habiltar',
            field=models.BooleanField(default=True, verbose_name='Habilitar Alarma RATA DEL CAMBIO'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ValorInicial',
            field=models.FloatField(default=1.0, verbose_name='Valor Inicial'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ValorMaximo',
            field=models.FloatField(default=20.0, verbose_name='Valor Maximo'),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ValorMinimo',
            field=models.FloatField(default=0.0, verbose_name='Valor Minimo'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Reintentos',
            field=models.IntegerField(default=3, verbose_name='Nro de Intentos'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Habilitar',
            field=models.BooleanField(default=True, verbose_name='Habilitar '),
        ),
        migrations.AlterField(
            model_name='tag',
            name='direccion',
            field=models.CharField(default='4:0', max_length=5, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='direccion_campo',
            field=models.CharField(default='4:0', max_length=5, verbose_name='Direccion de Campo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta1',
            field=models.CharField(choices=[('lt', 'Nivel Medido'), ('pt', 'Presión'), ('tt', 'Temperatura'), ('TOV', 'Volumen Total Observado '), ('NA', 'No Asignado'), ('GSV', 'Volumen Bruto Estandar'), ('NSV', 'Volumen Neto Estandar'), ('lta', 'Nivel de Agua Libre'), ('ays', 'Porcentaje de Agua y Sedimento')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta3',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='AREA 1 Informacion Customizada'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta4',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='AREA 2 Informacion Customizada'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta5',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='AREA 3 Informacion Customizada'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta6',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='AREA 4 Informacion Customizada'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id_Tk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.tk', verbose_name='ID del Tanque'),
        ),
    ]
