# Generated by Django 3.0.3 on 2020-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0004_auto_20201122_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='etiqueta3',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta4',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta5',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='etiqueta6',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ETIQUETA PARA USUARIOS'),
        ),
    ]
