# Generated by Django 3.0.3 on 2020-02-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0004_analogico_seg_pv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hs_Analogico_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vp', models.FloatField(default=1.0)),
                ('Timestamp', models.DateField()),
                ('id_Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Analogico_seg',
        ),
    ]
