# Generated by Django 3.0.3 on 2020-02-28 01:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0005_auto_20200226_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analogico_Hs0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
