# Generated by Django 3.2 on 2021-06-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0006_auto_20210602_1546'),
        ('acq', '0006_auto_20210612_0005'),
    ]

    operations = [
    ]
