# Generated by Django 3.0.3 on 2020-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0006_analogico_hs0'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hs_Analogico_0',
        ),
    ]
