# Generated by Django 3.0.3 on 2020-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0007_auto_20201125_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='fecha_subida_tct',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subido El:'),
        ),
    ]
