# Generated by Django 3.2.6 on 2021-08-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0007_merge_0006_auto_20210602_1546_0006_auto_20210612_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogico',
            name='H',
            field=models.FloatField(default=16.0),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='HH',
            field=models.FloatField(default=18.0),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='L',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='LL',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ValorMaximo',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='analogico',
            name='ValorMinimo',
            field=models.FloatField(default=0.0),
        ),
    ]
