# Generated by Django 3.0.3 on 2020-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0008_analogico_hs1_analogico_hs2_analogico_hs3_analogico_hs4_analogico_hs5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patiotanque',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='patiotanque',
            name='Descriptor',
            field=models.CharField(default='', max_length=120),
        ),
    ]
