# Generated by Django 3.2.6 on 2021-08-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0008_auto_20210807_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbmaestro',
            name='SercvicePort',
            field=models.IntegerField(default=5002),
        ),
        migrations.AlterField(
            model_name='mbesclavo',
            name='Paridad',
            field=models.CharField(choices=[('PAR', 'Par'), ('IMPAR', 'Impar')], default='PAR', max_length=5, verbose_name='solo para comunicacion serial'),
        ),
        migrations.AlterField(
            model_name='mbesclavo',
            name='Velocidad',
            field=models.IntegerField(choices=[('A', 9600), ('B', 19200), ('C', 38400)], default=19200, verbose_name='solo para comunicacion serial'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Paridad',
            field=models.CharField(choices=[('PAR', 'Par'), ('IMPAR', 'Impar')], default='PAR', max_length=5, verbose_name='solo para comunicacion serial'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Puerto',
            field=models.CharField(default='TCP_SRV', max_length=10),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Velocidad',
            field=models.IntegerField(choices=[(1, 9600), (2, 19200), (3, 38400)], default=1, verbose_name='solo para comunicacion serial'),
        ),
    ]
