# Generated by Django 3.0.3 on 2020-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0009_auto_20200429_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiotanque',
            name='Nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
