# Generated by Django 3.2.6 on 2021-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0009_auto_20210816_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbmaestro',
            name='IpDevice',
            field=models.CharField(default='127.0.0.1', max_length=100, verbose_name='Ip del Esclavo'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='IdDevice',
            field=models.IntegerField(default=1, verbose_name='Id del Esclavo'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Paridad',
            field=models.CharField(choices=[('PAR', 'Par'), ('IMPAR', 'Impar')], default='PAR', max_length=5, verbose_name='Paridad'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Puerto',
            field=models.CharField(choices=[('TCP_SRV', 'TCP_SRV'), ('serial1', 'COM1'), ('serial2', 'COM2'), ('serial3', 's0'), ('serial4', 's1')], default='TCP_SRV', max_length=10),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='SercvicePort',
            field=models.IntegerField(default=5002, verbose_name='Puerto de Servicio'),
        ),
        migrations.AlterField(
            model_name='mbmaestro',
            name='Velocidad',
            field=models.IntegerField(choices=[(1, 9600), (2, 19200), (3, 38400)], default=1, verbose_name='Tasa de baudios'),
        ),
    ]
