# Generated by Django 3.0.3 on 2020-05-28 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0010_auto_20200501_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analogico_Hs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
