# Generated by Django 3.0.3 on 2020-06-04 18:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0012_auto_20200604_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogico_hs',
            name='dataq',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
