# Generated by Django 3.0.3 on 2020-07-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0014_remove_analogico_hs_dataq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tct',
            name='Lt2',
        ),
        migrations.AddField(
            model_name='tct',
            name='Tov_1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tct',
            name='Tov_2',
            field=models.FloatField(default=1.0),
        ),
    ]
