# Generated by Django 3.0.3 on 2020-07-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0015_auto_20200702_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk',
            name='Descriptor',
            field=models.CharField(default='', max_length=120),
        ),
    ]
