# Generated by Django 3.0.3 on 2020-07-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0016_tk_descriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tk',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
