# Generated by Django 3.0.3 on 2020-07-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0017_auto_20200705_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tk',
            old_name='Descriptor',
            new_name='Descriptortortor',
        ),
    ]
