# Generated by Django 3.0.3 on 2020-07-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0018_auto_20200707_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tk',
            old_name='Descriptortortor',
            new_name='Descriptor',
        ),
    ]
