# Generated by Django 3.0.3 on 2020-07-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0019_auto_20200707_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk',
            name='tct_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
