# Generated by Django 3.0.3 on 2020-07-18 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0020_tk_tct_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tk',
            name='tct_file',
        ),
        migrations.AddField(
            model_name='tk',
            name='Descriptor_tct',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tk',
            name='fecha_subida_tct',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tk',
            name='tct_archivo',
            field=models.FileField(blank=True, upload_to='tct'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Descriptor',
            field=models.CharField(default='', max_length=120),
        ),
    ]
