# Generated by Django 3.0.3 on 2020-09-02 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0021_auto_20200718_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk',
            name='tct_nivel',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tk',
            name='tct_vol',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='tk',
            name='Descriptor_tct',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tk',
            name='fecha_subida_tct',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subido El:'),
        ),
        migrations.AlterField(
            model_name='tk',
            name='id_patioTanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acq.PatioTanque', verbose_name='Patio de Tanques'),
        ),
        migrations.AlterField(
            model_name='tk',
            name='tct_archivo',
            field=models.FileField(blank=True, upload_to='tct', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
