# Generated by Django 3.0.3 on 2020-09-16 19:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0022_auto_20200902_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk',
            name='tct_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='tk',
            name='tct_nivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
