# Generated by Django 3.0.3 on 2020-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0024_auto_20200923_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='Descriptor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tk',
            name='Descriptor_tct',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
