# Generated by Django 3.0.3 on 2020-09-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acq', '0025_auto_20200926_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='fecha_subida_tct',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Subido El:'),
        ),
    ]
